version: '3.8'

services:
  php-apache:
    image: php:8.1-apache
    container_name: php-apache
    volumes:
      - ./includes:/var/www/html
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: watchlist
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
